name: frailty_project_2019
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.2
  firebase_auth: ^0.11.1+7
  progress_dialog: ^1.1.0+1
  http: ^0.12.0+2
  json_serializable: ^3.0.0
  intl: ^0.15.8


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: SukhumvitSet
      fonts:
        - asset: fonts/SukhumvitSet-Text.ttf
          weight: 400
        - asset: fonts/SukhumvitSet-Bold.ttf
          weight: 700
        - asset: fonts/SukhumvitSet-Light.ttf
          weight: 300
        - asset: fonts/SukhumvitSet-Medium.ttf
          weight: 500
        - asset: fonts/SukhumvitSet-SemiBold.ttf
          weight: 600
        - asset: fonts/SukhumvitSet-Thin.ttf
          weight: 200

  assets:
    - images/settings.png
    - images/funny-elderly-couple-dancing-cartoon-vector-24002358.jpg
    - images/search-4.png
    - images/facebook.png
    