name: frailty_project_2019
description: A new Flutter application.

version: 1.0.2+8

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0+2
  path:
  google_sign_in: ^4.5.1
  firebase_auth: ^0.16.1
  progress_dialog: ^1.2.3
  http: ^0.12.1
  json_serializable: ^3.3.0
  intl: ^0.16.1
  auto_size_text: ^2.1.0

  flutter_thailand_provinces: 1.0.1

  flutter_rounded_date_picker: 1.0.4
  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: 1.0.1

  flutter_svg: ^0.17.4

  uuid: ^2.0.4

  flutter_cupertino_settings: ^0.1.0

  flutter_statusbar_text_color: ^0.1.2

  device_info: ^0.4.2+4

  apple_sign_in: ^0.1.0

  flutter_secure_storage: ^3.3.3

  sliding_up_panel: ^1.0.2
  flutter_swiper: ^1.1.6
  material_design_icons_flutter: 3.2.4096
  flutter_device_type: ^0.2.0

  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  shared_preferences: ^0.5.7+3

  pin_code_fields: ^3.0.1

  flutter_spinkit: ^4.1.2+1

  cupertino_icons: ^0.1.3

  splashscreen: ^1.2.0

  dynamic_theme: ^1.0.1
  flutter_slidable: ^0.5.4
  flutter_rounded_progress_bar: ^0.1.2

  connectivity: ^0.4.8+6
  indexed_list_view: ^1.0.9

  dots_indicator: ^1.1.0

  syncfusion_flutter_gauges: ^17.4.43-beta



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: SukhumvitSet
      fonts:
        - asset: fonts/SukhumvitSet-Text.ttf
          weight: 400
        - asset: fonts/SukhumvitSet-Bold.ttf
          weight: 700
        - asset: fonts/SukhumvitSet-Light.ttf
          weight: 300
        - asset: fonts/SukhumvitSet-Medium.ttf
          weight: 500
        - asset: fonts/SukhumvitSet-SemiBold.ttf
          weight: 600
    - family: THSarabunNew
      fonts:
        - asset: fonts/THSarabunNew Bold.ttf
          weight: 700
        - asset: fonts/THSarabunNew BoldItalic.ttf
          weight: 700
        - asset: fonts/THSarabunNew Italic.ttf
          weight: 400
        - asset: fonts/THSarabunNew.ttf
          weight: 400



  assets:
    - images/settings.png
    - images/funny-elderly-couple-dancing-cartoon-vector-24002358.png
    - images/search-4.png
    - images/facebook.png
    - images/qr-code-light.png
    - images/qr-code-dark.png
    - images/brands-and-logotypes.png
    - images/company.png
    - images/user.png
    - images/password.png
    - images/google.png
    - images/company-dark.png
    - images/password_light.png
    - images/user_light.png
    - images/address_dark.png
    - images/address_light.png
    - images/cake.png