name: frailty_project_2019
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.1.7+2
  path:
  flutter_cupertino_date_picker: ^1.0.12
  google_sign_in: ^4.0.11
  firebase_auth: ^0.14.0+8
  progress_dialog: ^1.2.0
  http: ^0.12.0+2
  json_serializable: ^3.2.3
  intl: ^0.16.0
  auto_size_text: ^2.1.0
  geolocator: ^5.1.5
  permission_handler: ^4.0.0

  uuid: ^2.0.2

  flutter_cupertino_settings: ^0.1.0
  device_info: ^0.4.1+1

  apple_sign_in: ^0.1.0

  flutter_secure_storage: ^3.3.1+1

  sliding_up_panel: ^0.3.6
  flutter_swiper: ^1.1.6
  material_design_icons_flutter: 3.2.4096
  flutter_device_type: ^0.2.0

  bloc: ^2.0.0
  flutter_bloc: ^2.0.0
  shared_preferences: ^0.5.4+3

  flutter_spinkit: ^4.0.0

  cupertino_icons: ^0.1.2

  splashscreen: ^1.2.0

  dynamic_theme: ^1.0.1
  flutter_slidable: ^0.5.4
  flutter_rounded_progress_bar: ^0.1.2

  connectivity: ^0.4.5+3
  indexed_list_view: ^1.0.8

  firebase_messaging: ^5.1.8
  firebase_in_app_messaging: ^0.1.0
  flutter_local_notifications: ^0.8.4

  syncfusion_flutter_gauges: ^17.3.26-beta



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  fonts:
    - family: SukhumvitSet
      fonts:
        - asset: fonts/SukhumvitSet-Text.ttf
          weight: 400
        - asset: fonts/SukhumvitSet-Bold.ttf
          weight: 700
        - asset: fonts/SukhumvitSet-Light.ttf
          weight: 300
        - asset: fonts/SukhumvitSet-Medium.ttf
          weight: 500
        - asset: fonts/SukhumvitSet-SemiBold.ttf
          weight: 600
    - family: THSarabunNew
      fonts:
        - asset: fonts/THSarabunNew Bold.ttf
          weight: 700
        - asset: fonts/THSarabunNew BoldItalic.ttf
          weight: 700
        - asset: fonts/THSarabunNew Italic.ttf
          weight: 400
        - asset: fonts/THSarabunNew.ttf
          weight: 400



  assets:
    - images/settings.png
    - images/funny-elderly-couple-dancing-cartoon-vector-24002358.png
    - images/search-4.png
    - images/facebook.png